require('./lib/persistance_entity')
require('./lib/persistance_json')
require('./lib/entity')
require('./lib/attribute')
require('./lib/attribute_types/text_type')
require('./lib/Information')
require('./lib/attribute_types/numeric_type')